### ISSUE TITLE
Decap CMS works only with "en" as default language

### ISSUE THREAD

**Issue by lsatok** [Hugolify/hugolify-admin#3]
## Description

Decap CMS works only when the default language of site is English. If I change the default language to something else CMS no longer works.

## Steps to reproduce

Start with Hugolify default template and make no changes.

1. Set following settings:

config/_default/hugo.yaml
```
    defaultContentLanguage: en
    languageCode: en
```

config/_default/params.yaml
```
admin:
  cms: decapcms 
  config:
    id: false 
  i18n:
    default_locale: fi 
    locales: '[en,fi]'
  netlify:
    identity: true 
```

config/_default/languages.yaml
```
fi:
  languageName: Finnish
  title: Otsikko
  weight: 1

en:
  languageName: English
  title: Title
  weight: 2

```

2. Open CMS -> localhost:1313/admin -> Verify that CMS can be accessed
3.  In hugo.yaml change `defaultContentLanguage` and `languageCode` to `fi`
4. Open CMS -> localhost:1313/admin

### EXPECTED
CMS can still be accessd

### ACTUAL
An error is thrown

``` 
Error loading the CMS configuration
Config Errors:
'collections[0].files[6].fields[3].label' must be string
'collections[0].files[6].fields[3].hint' must be string
Check your config.yml file.
 ```
